
name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Upload to server
      - uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:
          username: S{{secrets.EC2_USERNAME}} 
          server: S{{secrets.EC2_SERVER_IP}} 
          ssh_private_key: "{{secrets.EC2_SSH_PRIVATE_KEY}J" 
          local_path: './*'
          remote_path: '/var /www/html'
